### ISSUE TITLE
Add to collection via photo detail page

### ISSUE THREAD

**Issue by Caroga** [Piwigo/Piwigo-User-Collections#18]
Hi there!
Would it be possible to add a "add to collection" button on the detail page of the photo? 
You can now add photos from the album detail page, the overview of all the photos in the album. 
It would be helpful being able to do this when clicking viewing a photo instead of having to click back to the overview.

**Comment by mistic100** [comment]
This is already the case, perhaps you are using a theme witch does not implement picture buttons.

Relevant line in the plugin https://github.com/Piwigo/Piwigo-User-Collections/blob/master/include/events.inc.php#L217

And in the default template https://github.com/Piwigo/Piwigo/blob/master/themes/default/template/picture.tpl#L91

**Comment by Caroga** [comment]
Ow yeah I forgot to mention, I am indeed using a different theme: [bootstrap darkroom](https://piwigo.org/ext/extension_view.php?eid=831).

I will check if I can implement it. Thank you for this!

**Comment by Caroga** [comment]
I fixed it with your help, by adding the corresponding line to `template/picture_nav_buttons.tpl` which I found the most appropriate for the team.
Thank you very much!
