### ISSUE TITLE
User Collection / Gthumb compatibility

### ISSUE THREAD

**Issue by Pascaloub** [Piwigo/Piwigo-User-Collections#24]
Hi all,
first of all, I'm very glad to see a new updated version of User Collection which is a very usefull plugin. Thanks a lot for this work.

It seem's to me that this version is no longer compatible with the GThumb plugin's that we are too using here so we have to make a very difficult if not impossible choice between these two ;)

When GThumb is activated, the collection tools no longer appear on the images thumbnail of the album page, making it impossible to add/remove any image to a collection.

thx,

Pascal

Piwigo 12.2.0
PHP: 7.3.31
User Collections 12.a
GThumb+ 12.a

**Comment by Zacharieg** [comment]
Hi Pascaloub

Just to let you know that I resolved the issue, you can use Gthumb and User Collection with Bootstrap Darkroom now.
Let me know if that's resolved the problem for you.
